model_reasoning_summary = "detailed"
file_opener = "none"
show_raw_agent_reasoning = true
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
web_search = "live"

[features]
unified_exec = true
shell_snapshot = true

[tools]
sandbox_mode = "workspace-write"
approval_policy = "on-request"

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = true

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
